#!/bin/bash

echo "🔄 強制重新部署最新版本"
echo "======================"
echo ""

echo "🔧 方法 1: 觸發新的部署"
echo "在 GitHub 倉庫頁面："
echo "1. 前往: https://github.com/Alvinhung/perpdex-dashboard"
echo "2. 點擊 'Actions' 標籤頁"
echo "3. 點擊 'Deploy to GitHub Pages' workflow"
echo "4. 點擊 'Run workflow' 按鈕"
echo "5. 等待部署完成"
echo ""

echo "🔧 方法 2: 檢查本地版本"
echo "確認本地版本是最新："
echo "cd $(pwd)"
echo "pnpm build"
echo ""
echo "🔧 方法 3: 清除緩存"
echo "清除瀏覽器緩存："
echo "1. Ctrl+Shift+R (硬重新整理)"
echo "2. Ctrl+Shift+Delete (清除緩存)"
echo "3. 打開無痕模式測試"
echo ""

echo "📋 應該有的功能："
echo "✅ 滑鼠懸停 FDV 區間機率"
echo "✅ Vol/OI 健康度顏色指示"
echo "✅ 表格排序功能"
echo "✅ 搜尋功能"
echo "✅ 實時數據更新按鈕"
echo "✅ 響應式設計"
echo ""

echo "🔗 測試連結："
echo "本地: http://192.168.68.53:3000/"
echo "線上: https://alvinhung.github.io/perpdex-dashboard/"
echo ""

echo "💡 如果還是不對："
echo "1. 檢查本地版本是否正常"
echo "2. 確認 GitHub Actions 部署最新代碼"
echo "3. 可能需要清除 GitHub Pages 緩存"