#!/bin/bash

echo "🚀 PerpDex Dashboard 啟用指南"
echo "================================"
echo ""
echo "📋 當前狀況:"
echo "✅ Dashboard 本地運行正常: http://192.168.68.53:3000/"
echo "✅ 生產版本已構建完成"
echo "✅ 所有文件準備就緒"
echo ""
echo "🔧 需要 GitHub 設置:"
echo ""
echo "步驟 1: 建立 GitHub 倉庫"
echo "--------------------------"
echo "1. 前往: https://github.com/new"
echo "2. 倉庫名稱: perpdex-dashboard"  
echo "3. 設為: Public (重要!)"
echo "4. 不要勾選 'Add a README file'"
echo "5. 點擊 'Create repository'"
echo ""
echo "步驟 2: 連接並推送"
echo "-------------------"
echo "在終端執行:"
echo "cd $(pwd)"
echo "git remote set-url origin https://github.com/YourUsername/perpdex-dashboard.git"
echo "git push --set-upstream origin main"
echo ""
echo "步驟 3: 啟用 GitHub Pages"
echo "-------------------------"
echo "1. 前往: https://github.com/YourUsername/perpdex-dashboard/settings/pages"
echo "2. Source: 選擇 'GitHub Actions'"
echo "3. 點擊 'Save'"
echo "4. 等待 2-3 分鐘部署完成"
echo ""
echo "步驟 4: 分享連結"
echo "---------------"
echo "最終連結: https://YourUsername.github.io/perpdex-dashboard"
echo ""
echo "🔗 立即可用 (同網絡):"
echo "http://192.168.68.53:3000/"
echo ""
echo "📱 QR Code 可用於快速分享"
echo ""
echo "💡 提示: 如果需要協助建立倉庫，請告訴我你的 GitHub 用戶名！"